topics = [
    {"name": "Theory of Structures", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-theory-of-structures/"},
    {"name": "Structural Analysis", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-structural-analysis/"},
    {"name": "RCC Structures Design", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-rcc-structures-design/"},
    {"name": "Concrete Technology and Design of Concrete Structures", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-concrete-technology-and-design-of-concrete-structures/"},
    {"name": "Design of Masonry Structures", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-design-of-masonry-structures/"},
    {"name": "Design of Steel Structures", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-design-of-steel-structures/"},
    {"name": "Building Construction", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-building-construction/"},
    {"name": "Building Materials", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-building-materials/"},
    {"name": "Building Maintenance", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-building-maintenance/"},
    {"name": "Strength of Materials", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-strength-of-materials/"},
    {"name": "Applied Mechanics and Graphic Statics", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-applied-mechanics-and-graphic-statics/"},
    {"name": "Elements of Remote Sensing", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-elements-of-remote-sensing/"},
    {"name": "Soil Mechanics and Foundation", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-soil-mechanics-and-foundation/"},
    {"name": "Environmental Engineering", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-environmental-engineering/"},
    {"name": "Hydraulics and Fluid Mechanics", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-hydraulics-and-fluid-mechanics/"},
    {"name": "Irrigation Engineering", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-irrigation-engineering/"},
    {"name": "Waste Water Engineering", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-waste-water-engineering/"},
    {"name": "Water Supply Engineering", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-water-supply-engineering/"},
    {"name": "Airport Engineering", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-airport-engineering/"},
    {"name": "Docks and Harbor Engineering", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-docks-and-harbor-engineering/"},
    {"name": "Highway Engineering", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-highway-engineering/"},
    {"name": "Railway Engineering", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-railway-engineering/"},
    {"name": "Tunnel Engineering", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-tunnel-engineering/"},
    {"name": "Surveying", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-surveying/"},
    {"name": "Construction Planning and Management", "link": "https://www.examveda.com/civil-engineering/practice-mcq-question-on-construction-planning-and-management/"}
]
